name: Nextjs-App Deploy with GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into AWS Lightsail and Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /path/to/your/app
            npm install
            npm audit fix --force
            npm run build
            pm2 start next-app
            pm2 save
            node -v
            npm -v
            pm2 list
